export const ACTION_TYPES = {
  INITIALIZING: 'INITIALIZING',
  INIT_COMPLETE: 'INIT_COMPLETE',
  LOGGING_IN: 'LOGGING_IN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGGED_IN: 'LOGGED_IN',
  LOGGED_OUT: 'LOGGED_OUT',
  UPDATE_USER: 'UPDATE_USER',
  SET_THEME: 'SET_THEME'
};
